name: "Terraform Destroy"

on:
  workflow_dispatch: # This makes it a manual button in GitHub UI

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    name: "Destroy Infrastructure"
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-central-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
